### ISSUE TITLE
Create Slack & Gitter Chat Channel

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#11]
Hi.

This would be an awesome work to make Gitter and Slack chat channel for who have questions and need help.

[Gitter](https://gitter.im)

[Slack](https://slack.com)

We can invite them to slack.

Thanks.

**Comment by unitycoder** [comment]
there is already popular unity slack: https://unitydevs.slack.com/
& unity discord https://forum.unity3d.com/threads/discord-unity-developer-hub.417893/
and many smaller ones for unity devs, so might not be worth the trouble?

**Comment by EmpireWorld** [comment]
Right, but i mean a chat channel specially for Unity Library.

**Comment by unitycoder** [comment]
yeah, could try it then. (actually that might be good place for planning requests and new repositories, instead of posting all as issues right away)

**Comment by EmpireWorld** [comment]
Good, you got me! so make one and invite us.

**Comment by unitycoder** [comment]
there is now https://unitylibrary.slack.com/

but need to setup automatic joining page.. something like https://github.com/outsideris/slack-invite-automation unless there are some other options to do that?

**Comment by unitycoder** [comment]
nevermind, could someone try to join using this link: https://join.slack.com/t/unitylibrary/shared_invite/MjE1MDA2NzExNDEwLTE1MDA0OTE5NzktOGJmYTI0ZDlkNA

**Comment by EmpireWorld** [comment]
@unitycoder You can make [heroku.com](https://heroku.com) slack in but the link you shared is better than it.

**Comment by EmpireWorld** [comment]
@unitycoder What about Gitter channel?

**Comment by unitycoder** [comment]
https://gitter.im/UnityCommunity/ 
*never used gitter before, if there is something else to setup can you check?

**Comment by EmpireWorld** [comment]
All done. nothing more, thanks.
