### ISSUE TITLE
Add 2D Follow Rigidbody Script

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#13]
Hi.

Same as #9 (Add 2D Follow Script) but uses **Rigidbody2D** instead of direct manipulation to **transform.position**.

Also now we should use **FixedUpdate** instead of **Update**.

So we should use `rigidbody2D.MovePosition ();` instead of `transform.position`.

Make sure to add all features from #9.

Thanks.

**Comment by Lootheo** [comment]
Added the feature in 34119349ee73f81a6d2a4f5e85c107d93eac4f29 , might need to move to a more specific folder in the future?

**Comment by EmpireWorld** [comment]
Good job, the folder is nice fit, but we can move it to something like **Physics**.
