### ISSUE TITLE
Update Old Shaders

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#14]
Hi.

We need to update the below shaders:

DebugNormalsTangets
Equirectangular
LerpColorNearToFarPlane
VertexColorMesh
UnlitFakeCurved

If you found any old shader please post it here.

Thanks.

**Comment by Lootheo** [comment]
Corrected the shaders to adapt for the new Unity.

**Comment by EmpireWorld** [comment]
Nice job. thanks.

**Comment by EmpireWorld** [comment]
@Lootheo Please reference the working issue in your commits. thanks.
