### ISSUE TITLE
Create Trello Board

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#17]
Hi.

Is it good idea to create a trello board?

[:sparkles: Trello](https://trello.com)

Thanks.

**Comment by unitycoder** [comment]
can you try if can access/use this?
https://trello.com/b/SIfiVLYi/unity-library

**Comment by EmpireWorld** [comment]
I can see the board by i can't modify it until you invite us.

You should invite us to the board.

Thanks.

**Comment by unitycoder** [comment]
try this public invitation link
https://trello.com/invite/b/SIfiVLYi/2c640a78d533382340567e625708c9e0/unity-library

**Comment by EmpireWorld** [comment]
Nice, thanks, this is awesome.

I will add it to readme file.

**Comment by EmpireWorld** [comment]
@unitycoder Please give me full permissions. Also make Unity Community Organization in the Trello and add this board to the organization then invite us as team.

**Comment by EmpireWorld** [comment]
@unitycoder Thanks you are awesome. you made discord channel, also give me full permissions anywhere, i like to manage them.

**Comment by EmpireWorld** [comment]
@unitycoder I made a new board for the Unity Library. https://trello.com/b/1sOcvQzd/unity-library
