### ISSUE TITLE
Move the whole library to a Unity Project

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#18]
Hi.

Is it a good idea to move the whole library files such as shaders, scripts, ... to a new empty unity project?

It makes our works easier and we can check our scripts together.

If you accept it, i will do it.

Thanks.

**Comment by unitycoder** [comment]
yeah, that would help

**Comment by EmpireWorld** [comment]
So i am going to move it to an empty unity project.

Thanks.

**Comment by Lootheo** [comment]
I was thinking about adding some scenes that shows what each shader/script does, maybe moving it to a project can really help with that. I'm In

**Comment by EmpireWorld** [comment]
Unity Project Created, [fead9c8](https://github.com/UnityCommunity/UnityLibrary/commit/df9377c7efc5db4d6301af4fdba809c91bae4026)

Close.
