### ISSUE TITLE
Add Namespace to All Scripts

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#21]
Hi.

If someone wants to include the whole library in it's own project, there might be some name collisions. or even one script might throw name exceptions.

So it is good idea to choose a namespace for all of the UnityLibrary scripts and commit the namespace to all of them.

I recommend **UnityLibrary** namespace for all scripts.

Any suggestions for namespace name is appreciated.

If all accept it, we will go to add namespace to all scripts.

Thanks.

**Comment by Lootheo** [comment]
I think UnityLibrary is great, just need to make sure that there is no other popular project with that name

**Comment by EmpireWorld** [comment]
@Lootheo No, there is nothing, i searched for it a while ago and just found this repo.

**Comment by Lootheo** [comment]
Added the namespace, might need a check to close the issue.

**Comment by EmpireWorld** [comment]
It was better to make a pull request.

There are many of them, just check them in Unity itself and make sure there is no error.

**Comment by EmpireWorld** [comment]
@Lootheo All done, there is no error. Close.
