### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by unitycoder** [UnityCommunity/UnityLibrary#3]
(can post requests here)

Some ideas for now
- Stringbuilder example for concatenation without garbage collection problems
- Camera controllers for common use (like: orbit, fly, lookaround, follow..)
- Mathi. library (same as Mathf. but just for ints, should be faster without using System.Math. that Mathf. uses) *maybe can use SIMD later also?

**Comment by unitycoder** [comment]
old post cleanup, and better to have separate issues for each topic

**Comment by EmpireWorld** [comment]
@unitycoder Nice job. i wanted to suggest you.
