### ISSUE TITLE
Remove script templates for Javascript

### ISSUE THREAD

**Issue by agarcialeon** [UnityCommunity/UnityLibrary#33]
Javascript support has been deprecated in Unity3D as a programming language (note that I'm not pointing to Javascript plugins when you export for WebGL platform). So script templates should be removed from the library or move them to a legacy folder.

**Comment by unitycoder** [comment]
yes, i'd say just remove - no need to keep (since they are totally useless)

**Comment by Atknssl** [comment]
This issue is solved in #50, please close.
