### ISSUE TITLE
Bug when opening in  Unity 2017.1.0f3

### ISSUE THREAD

**Issue by LashaBuxo** [UnityCommunity/UnityLibrary#40]
When I'm opening the project in a version, which is mentioned in ProjectSettings/Projectversion.txt file, it has 1 error: 

> Assets/Scripts/Editor/ContextMenu/GetVideoAspectRatioEditor.cs(22,36): error CS1061: Type `UnityEngine.Video.VideoPlayer' does not contain a definition for `height' and no extension method `height' of type `UnityEngine.Video.VideoPlayer' could be found. Are you missing an assembly reference?

**Comment by LashaBuxo** [comment]
I'll fix this issue by replacing `VideoPlayer.height/width` to `VideoPlayer.texture.height/width` . I already tested it and works like a charm, so I make pull request for fixing this bug for users trying to open the project in 2017 version.

**Comment by LukaTchumburidze** [comment]
[Lashaaaaaa!!!!](https://drive.google.com/file/d/18_mxXbph1HSIk9XLStPyhLWD773LKm1O/view?usp=sharing)

**Comment by unitycoder** [comment]
thanks, merged

**Comment by xhhzuikeaiya** [comment]
thanks
