### ISSUE TITLE
Update project version to the latest LTS version?

### ISSUE THREAD

**Issue by LittleCopernicus** [UnityCommunity/UnityLibrary#43]
https://github.com/UnityCommunity/UnityLibrary/blob/4e92323a9ba1add50e282439b635b4780788660f/ProjectSettings/ProjectVersion.txt#L1

Update project version to the latest LTS version?

**Comment by unitycoder** [comment]
yeah could upgrade to 2018.4 lts, if somebody wants to check if scripts still compile there ok
