### ISSUE TITLE
Add Object pooling system

### ISSUE THREAD

**Issue by Sacristan** [UnityCommunity/UnityLibrary#6]

**Comment by EmpireWorld** [comment]
Hi.

Some kind of scripts like Object pooling can be found by a small search.

Here is a list of object pooling systems:

- [SimplePool.cs](https://gist.github.com/quill18/5a7cfffae68892621267)
- [RecyclerKit](https://github.com/prime31/RecyclerKit)

And some tutorials:

- [Object pooling for Unity3D](https://blogs.msdn.microsoft.com/dave_crooks_dev_blog/2014/07/21/object-pooling-for-unity3d/)
- [Object pooling Unity](https://www.raywenderlich.com/136091/object-pooling-unity)
- [Object pools](http://catlikecoding.com/unity/tutorials/object-pools/)

We don't need to copy paste them to Unity Library, we need to provide missing components.

But we will add a very simple object pooling system to the Unity Library.

Thanks.

**Comment by Sacristan** [comment]
@EmpireWorld Is it possible that You do this matter ? No time for me to do this for quite some time.

**Comment by EmpireWorld** [comment]
I will do it, thanks.

Let me know if you have any further questions. i want to close this issue.

**Comment by EmpireWorld** [comment]
Everyone is welcome to add simple object pooling system.

**Comment by unitycoder** [comment]
some advanced pooling system here, maybe can have a look/test
https://github.com/Nordeus/Unite2015/tree/master/GenericPool

**Comment by EmpireWorld** [comment]
@unitycoder Good resource point. thanks for sharing.

**Comment by unitycoder** [comment]
closing this old issue as there was one submission for this now:
https://github.com/UnityCommunity/UnityLibrary/pull/48
