### ISSUE TITLE
Where is Contributing Guidelines?

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#7]
Hi.

I have checked the files inside of this repository but i didn't find anything that contains Contribution guidelines.

GitHub provides a special file for this named `CONTRIBUTING`, plus `CODE_OF_CONDUCT`.

You can add these files to the repository to let people contribute and collaborate with this project.

Thanks.

**Comment by unitycoder** [comment]
ill have a look (or anyone else, feel free to add)
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by EmpireWorld** [comment]
Contribution Guidelines Added. (Thanks to @unitycoder)
