### ISSUE TITLE
Add 2D Follow Script

### ISSUE THREAD

**Issue by EmpireWorld** [UnityCommunity/UnityLibrary#9]
Follow Utility.

We should be able to attach it to any object that we want follows another object.

This follow script can have these settings:

- **offset** (Vector3): The position offset for the follower.
- **followType** (Enum): MoveTowards, Lerp, SmoothDamp and Acceleration Enum, Also each follow type has it's own settings.

```csharp
public enum FollowType {
  MoveTowards,
  Lerp,
  Slerp,
  SmoothDamp,
  Acceleration
}
```

- **speed** (You can use it where you need it): The speed of the follower.
- **time** (You can use it where you need it for Lerp, MoveTowards, ...): The time for movement, Also you can use it as smooth time for SmoothDamp.
-  **bounds** (Bounds, BoxCollider2D, Vector2, ...): Can be anything, a width and height or a box collider 2d or an bounds class, also there should be an option to disable it.

EDIT: Acceleration movement http://answers.unity3d.com/answers/29757/view.html

Any more suggestions are welcome. 😄 

Looking for Rigidbody2D follow script? Find it at #13 

Thanks.

**Comment by Lootheo** [comment]
Sounds like a fun thing to check, I'll give it a try today.

**Comment by Lootheo** [comment]
Added a sample on last commit, I'm not sure what you mean by acceleration follow, will add if explained.

**Comment by EmpireWorld** [comment]
Acceleration follow means the object increases speed over time. Gradually moving an object.

Here is a nice resource: http://answers.unity3d.com/answers/29757/view.html

Resource Added to issue.

Thanks.

**Comment by Lootheo** [comment]
The script was added in commit 6f5c171911bef947890914859c459b007401c8e6
It's called Follow2D
Just missing the acceleration follow.

**Comment by EmpireWorld** [comment]
I know.

But we are waiting for acceleration follow to be added, then we close this issue.

Thanks.

**Comment by Lootheo** [comment]
Added the acceleration follow in 711f635c422dd7ecccd18173452cccd3a480b384

**Comment by EmpireWorld** [comment]
Nice job.
